title: "My Jekyll Blog"
description: "日々の学びや考えを記録するブログです。"
timezone: Asia/Tokyo
lang: ja-JP
theme: jekyll-theme-chirpy

github:
  username: nollie540kickflip

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache

paginate: 10
