title: "試行錯誤ログ"
description: "「やってみた」「ハマった」「解決した」の記録。"
timezone: Asia/Tokyo
lang: ja-JP
theme: jekyll-theme-chirpy

# プロフィール画像（左サイドバーの一番上の丸いアイコン）
# 画像のURLを指定します。自分の画像を使う場合は画像をリポジトリに入れてそのパスを指定します。
avatar: "https://github.com/nollie540kickflip.png"

github:
  username: nollie540kickflip

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

markdown: kramdown
highlighter: rouge
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

paginate: 10
